name: tencent_keyboard_visibility
description: A new Flutter keyboard visibility package.
version: 1.0.1
homepage: https://github.com/RoleWong/tencent_keyboard_visibility

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: